= Project Proposal

== Motivation

I'm going to try and create an app that will help for traveling purposes.  On the homepage of the app you can select from certain locations.  Then after selecting the locations, some good site locations or places to visit will be listed.  The target audience for this app is just people wanting to learn more about places outside of the US or are interested in travel like myself.  Really my motivation behind the app is because im interested in learning more about some of these common travel destinations, as I do plan on one day visiting them.  Something like a rough version of Gogobot will be soemthing I base my app on.  I like the idea of selecting a place and then list some important items like attractions, hotels, and food.    

The UI for my app will be pretty simple.  I will have some different views though forsure.  The homepage will consist of the title of my app and the tourist attractions listed in my small app.  Once clicking a location you will be taken to another page with information like attractions and good food to try.  With that being said, I will have back buttons on all of these pages following the homepage so the user can easily go back.  A goal of my app will be to make it very easy to use and follow.  